### ISSUE TITLE
Relation to SAP

### ISSUE THREAD

**Issue by roman0701** [sapmentors/SITregParticipant#10]
I would add a list with possible relations to SAP to the input field. This will make live easier when working with the data later.

**Comment by gregorwolf** [comment]
You're completely right. We want to use the list used in http://www.sithh.de/sitreg/. I haven't implemented the backend service yet as I want to have a solution that supports i18n.

**Comment by gregorwolf** [comment]
The backend provides now the OData entity for [RelationToSAP](https://github.com/sapmentors/SITreg/issues/6). Please fill the Drop-Down with it.

**Comment by mokadiri** [comment]
Hallo gregorwolf 

i think the log on language isn't determined in the RelationToSAP.hdbtablefunction: 
 SELECT SESSION_CONTEXT('LOCALE') INTO lv_locale FROM DUMMY;

When u call the Service https://hanamdcp1933806579trial.hanatrial.ondemand.com/com/sap/sapmentors/sitreg/odataparticipant/service.xsodata/RelationToSAP in the Browser u get values of all languages and when i tried to bind it in the combobox i received an error. 
i could bind the combobox after adjusting the RelationToSAP.hdbtablefunction to this: 

FUNCTION "SITREG"."com.sap.sapmentors.sitreg.odataparticipant.procedures::RelationToSAP" ()
RETURNS TABLE ("RelationToSAP" NVARCHAR (1), "Description" NVARCHAR (250))
LANGUAGE SQLSCRIPT SQL SECURITY INVOKER AS
BEGIN
    DECLARE lv_locale NVARCHAR (2);
    DECLARE lv_count INT := 0;
    
        RETURN SELECT "RelationToSAP","Description" FROM "com.sap.sapmentors.sitreg.data::SITreg.RelationToSAP"
          WHERE "Language" = 'en';

    
END;

but i know that don't solve the problem of current user language requirement.

**Comment by gregorwolf** [comment]
Hi @mokadiri, the error did not occur in my environment. I've also deployed my latest checkin to https://sitregparticipant-s0001142741trial.dispatcher.hanatrial.ondemand.com/ where you can give it a try directly. If the error still occurs please check if in the request header

Accept-Language:en

is sent. Sorry that I've already solved this issue now. But as you haven't pushed your code I needed a test environment. So it was the easiest to fix this issue.

**Comment by gregorwolf** [comment]
@roman0701 please retest and close this issue if fixed.

**Comment by mokadiri** [comment]
Hi @gregorwolf , 
i get the same error when i test ur link : 

![error](https://cloud.githubusercontent.com/assets/18596340/17459318/f37370ca-5c32-11e6-9bba-3649c73ce8c0.jpg)

{
	"message": "HTTP request failed",
	"headers": {
		"Content-Type": "application/xml;charset=utf-8",
		"content-language": "de-DE",
		"Content-Length": "227"
	},
	"statusCode": "500",
	"statusText": "Internal Server Error",
	"responseText": "<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code/><message xml:lang=\"en-US\">Service exception: [359] string is too long</message></error>"
}

**Comment by gregorwolf** [comment]
What response from the server do you see in the browser developer tools?

**Comment by mokadiri** [comment]
--7066983AE50EF7FAECA5EE7557F8DB540
Content-Type: application/http
Content-Length: 356
content-transfer-encoding: binary

HTTP/1.1 500 Internal Server Error
Content-Type: application/xml;charset=utf-8
content-language: de-DE
Content-Length: 227

<?xml version="1.0" encoding="utf-8" standalone="yes"?><error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><code/><message xml:lang="en-US">Service exception: [359] string is too long</message></error>
--7066983AE50EF7FAECA5EE7557F8DB540
Content-Type: application/http
Content-Length: 228
content-transfer-encoding: binary

HTTP/1.1 500 Internal Server Error
Content-Type: application/json
content-language: de-DE
Content-Length: 112

{ "error": { "code": "", "message": { "lang": "en-US", "value": "Service exception: [359] string is too long"}}}
--7066983AE50EF7FAECA5EE7557F8DB540--

**Comment by gregorwolf** [comment]
OK, as this is a backend issue I will track it further in [Create i18n enabled service to provide content for Relation to SAP drop down list #6](https://github.com/sapmentors/SITreg/issues/6)

**Comment by gregorwolf** [comment]
Please install the latest backend version with the [commit](https://github.com/sapmentors/SITreg/commit/1abec3441b6f0b510befa0026cca8eaefc6c41e0) that should fix the issue.

**Comment by mokadiri** [comment]
it works fine now.
