### ISSUE TITLE
Info-Button only shows the dialog the first time when pressed

### ISSUE THREAD

**Issue by ByteDoc** [sapmentors/SITregParticipant#13]
First click on Info-Button in Master Header opens the dialog, further button presses only cause this error:

Uncaught Error: The object with ID __html1 was destroyed and cannot be used anymore.setParent @ sap-ui-core.js:490

**Comment by gregorwolf** [comment]
Thank you for testing. Please refresh the test page and try again. If fixed please close issue.

**Comment by ByteDoc** [comment]
had to clear cache/restart Chrome (refresh was not sufficient), but dialog is opening every time now, working
