### ISSUE TITLE
Participantlist limited at 100 (default size limit odata model)

### ISSUE THREAD

**Issue by vfweiss** [sapmentors/SITregParticipant#15]
Due to the default sizelimit (100) in the model and growing not enabled on the sap.m.Table for the Participantlist in the detail view, you will only see the first 100 entries.

**Comment by gregorwolf** [comment]
If you have a solution for the issue please assign yourself and fix it. Thanks.

**Comment by vfweiss** [comment]
Fixed with pull request #16
