### ISSUE TITLE
Register / Edit Buttons at top of dialogue window or above List section

### ISSUE THREAD

**Issue by ATinMuenchen** [sapmentors/SITregParticipant#5]
Suggest to place Register / Edit Buttons at top of dialogue window, or directly above the List section, to make them visible without any scrolling.

**Comment by gregorwolf** [comment]
I've just tried the app with the Google Chrome phone simulator. The "Register" button is always visible when you are on the detail screen of an event:

![register-iphone](https://cloud.githubusercontent.com/assets/2639535/17361162/46679174-596f-11e6-85cb-1e217cba2fee.png)

Having the action buttons in the lower right corner of the screen fits the [SAP Fiori Design Guidelines](https://experience.sap.com/fiori-design-web/floorplans/split-screen/#examples).
