### ISSUE TITLE
Attachments button don´t work

### ISSUE THREAD

**Issue by roman0701** [sapmentors/SITregParticipant#9]
If I click the attachments button a white stripe in the upper edge of the right part of the window is opening but without content or functions.

Bug or feature?

**Comment by gregorwolf** [comment]
Feature of the app generation wizard. I think we should remove the additional tab. Has no planned functionality. Hope @mokadiri can take care about that.

**Comment by gregorwolf** [comment]
@roman0701 please retest and close if fixed.
